import Head from 'next/head';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';

export default function Home() {
  return (
    <div>
      <Head>
        <title>SBS tm</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Let`s Study' message='ketuk tombol Start untuk mulai belajar'  />
      <Instagram />
    </div>
  );
}
